name: Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  workflow_dispatch: {}

env:
  AR_REPO_LOCATION: "europe-west3-docker.pkg.dev"

jobs:
  build_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest

    name: Build frontend image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/quiz-hyligotchi

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: ${{ env.AR_REPO_LOCATION }}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
